In [1]:
# Experiment 5 - R Programming
# Missing Data and Conditional Statements

x <- c(11, NA, 13, NA)
x

[1] 11 NA 13 NA

In [2]:
is.na(x)

[1] FALSE  TRUE FALSE  TRUE

In [3]:
which(is.na(x))

[1] 2 4

In [4]:
sum(is.na(x))

[1] 2

In [5]:
mean(x)

[1] NA

In [6]:
mean(x, na.rm = TRUE)

[1] 12

In [7]:
y <- na.omit(x)
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [8]:
x <- 5

if(x > 4) {
  print(x * 3)
}

[1] 15

In [10]:
x <- 3

if(x > 4) {
  print(x * 3)
}

In [11]:
x <- 6

if(x > 3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is more than 3"

In [12]:
x <- 2

if(x > 3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is less than 3"

In [13]:
x <- 5

if(x == 3) {
  x <- x - 1
} else if(x < 3) {
  x <- x + 5
} else {
  x <- 2 * x
}

x

[1] 10

In [14]:
x <- 2

if(x == 3) {
  x <- x - 1
} else if(x < 3) {
  x <- x + 5
} else {
  x <- 2 * x
}

x

[1] 7

In [15]:
x <- 3

if(x == 3) {
  x <- x - 1
} else if(x < 3) {
  x <- x + 5
} else {
  x <- 2 * x
}

x

[1] 2

In [16]:
x <- 1:10

ifelse(x < 6, x^2, x + 1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [17]:
x <- c(7, 9, 8, 4)

ifelse(x %% 2 == 0, "even number", "odd number")

[1] "odd number"  "odd number"  "even number" "even number"

In [18]:
switch(2, "apple", "banana", "orange")

[1] "banana"

In [19]:
switch(1, "apple", "banana", "orange")

[1] "apple"

In [20]:
switch("colour",
       colour = "blue",
       gender = "male",
       volume = 50)

[1] "blue"

In [21]:
x <- c(10, 15, 8, 14, 6, 12)
x

[1] 10 15  8 14  6 12

In [22]:
which(x == 14)

[1] 4

In [23]:
which(x != 12)

[1] 1 2 3 4 5

In [24]:
which(x > 10)

[1] 2 4 6

In [25]:
x <- matrix(nrow = 3, ncol = 3, data = 1:9)
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [26]:
which.min(x)
which.max(x)
which(x %% 2 == 1)
which(x %% 2 == 1, arr.ind = TRUE)

[1] 1

[1] 9

[1] 1 3 5 7 9

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3